# VIF Filtering for Dataset

Results will be uploaded into VIF_test.csv, and if it works out well then I'll make VIF_counts.csv and VIF_percents.csv

### Import Libraries

In [18]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

### Import test dataset (jolts_counts.csv)

In [14]:
jolts_counts = pd.read_csv('jolts_counts.csv')

jolts_counts = jolts_counts.drop(['date'], axis=1)

jolts_counts.head()

,"Hires: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Job Openings: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Layoffs and Discharges: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Other separations: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Quits: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Total Separations: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Hires: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Job Openings: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Layoffs and Discharges: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Quits: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)",...,"Layoffs and Discharges: State and local government education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Other separations: State and local government education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Quits: State and local government education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Total Separations: State and local government education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Hires: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Job Openings: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Layoffs and Discharges: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Other separations: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Quits: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Total Separations: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)"
0,5426.0,5088.0,2018.0,340.0,2882.0,5240.0,78.0,68.0,24.0,38.0,...,42.0,11.0,45.0,98.0,105.0,277.0,44.0,19.0,52.0,115.0
1,5722.0,5234.0,2220.0,377.0,3245.0,5842.0,81.0,70.0,25.0,45.0,...,22.0,16.0,58.0,96.0,127.0,255.0,33.0,23.0,56.0,112.0
2,5303.0,5097.0,1855.0,323.0,3053.0,5231.0,67.0,70.0,28.0,43.0,...,19.0,11.0,40.0,70.0,124.0,242.0,27.0,16.0,72.0,115.0
3,5528.0,4762.0,2133.0,379.0,3054.0,5566.0,86.0,58.0,32.0,42.0,...,13.0,11.0,45.0,69.0,128.0,243.0,26.0,17.0,68.0,111.0
4,5204.0,4615.0,1883.0,367.0,3163.0,5414.0,86.0,65.0,27.0,48.0,...,12.0,12.0,34.0,59.0,143.0,288.0,48.0,22.0,57.0,127.0

### Start VIF Filtering

In [15]:
# VIF Filter jolts_counts

X_vif = add_constant(jolts_counts)
vif_data = pd.DataFrame()
vif_data["feature"] = X_vif.columns
vif_data["VIF"] = [variance_inflation_factor(X_vif.values, i) 
                    for i in range(X_vif.shape[1])]
print("Initial VIFs:\n", vif_data)

C:\Users\samee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\statsmodels\regression\linear_model.py:1782: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
C:\Users\samee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

Initial VIFs:
                                                feature  VIF
0                                                const  0.0
1    Hires: Total nonfarm - Level in Thousands, Mon...  inf
2    Job Openings: Total nonfarm - Level in Thousan...  inf
3    Layoffs and Discharges: Total nonfarm - Level ...  inf
4    Other separations: Total nonfarm - Level in Th...  inf
..                                                 ...  ...
962  Job Openings: State and local government, excl...  inf
963  Layoffs and Discharges: State and local govern...  inf
964  Other separations: State and local government,...  inf
965  Quits: State and local government, excluding e...  inf
966  Total Separations: State and local government,...  inf

[967 rows x 2 columns]

In [17]:
print(list(jolts_counts.columns))

['Hires: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Other separations: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Alaska - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Alaska - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Alaska - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Alaska - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Alaska - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Arizona - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Arizona - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Arizona - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Arizona - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Arizona - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Arkansas - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Arkansas - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Arkansas - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Arkansas - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Arkansas - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in California - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in California - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in California - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in California - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in California - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Colorado - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Colorado - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Colorado - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Colorado - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Colorado - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Connecticut - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Connecticut - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Connecticut - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Connecticut - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Connecticut - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Delaware - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Delaware - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Delaware - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Delaware - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Delaware - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in District of Columbia - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in District of Columbia - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in District of Columbia - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in District of Columbia - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in District of Columbia - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Florida - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Florida - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Florida - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Florida - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Florida - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Georgia - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Georgia - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Georgia - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Georgia - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Georgia - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Hawaii - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Hawaii - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Hawaii - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Hawaii - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Hawaii - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Idaho - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Idaho - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Idaho - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Idaho - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Idaho - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Illinois - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Illinois - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Illinois - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Illinois - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Illinois - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Indiana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Indiana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Indiana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Indiana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Indiana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Iowa - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Iowa - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Iowa - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Iowa - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Iowa - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Kansas - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Kansas - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Kansas - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Kansas - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Kansas - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Kentucky - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Kentucky - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Kentucky - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Kentucky - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Kentucky - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Louisiana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Louisiana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Louisiana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Louisiana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Louisiana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Maine - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Maine - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Maine - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Maine - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Maine - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Maryland - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Maryland - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Maryland - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Maryland - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Maryland - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Massachusetts - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Massachusetts - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Massachusetts - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Massachusetts - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Massachusetts - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Michigan - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Michigan - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Michigan - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Michigan - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Michigan - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Minnesota - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Minnesota - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Minnesota - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Minnesota - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Minnesota - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Mississippi - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Mississippi - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Mississippi - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Mississippi - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Mississippi - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Missouri - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Missouri - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Missouri - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Missouri - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Missouri - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Montana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Montana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Montana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Montana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Montana - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Nebraska - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Nebraska - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Nebraska - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Nebraska - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Nebraska - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in Nevada - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in Nevada - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in Nevada - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in Nevada - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in Nevada - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in New Hampshire - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in New Hampshire - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in New Hampshire - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in New Hampshire - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in New Hampshire - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in New Jersey - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in New Jersey - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in New Jersey - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in New Jersey - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in New Jersey - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in New Mexico - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in New Mexico - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in New Mexico - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in New Mexico - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in New Mexico - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in New York - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in New York - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in New York - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in New York - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in New York - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in North Carolina - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Job Openings: Total nonfarm in North Carolina - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Layoffs and Discharges: Total nonfarm in North Carolina - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Quits: Total nonfarm in North Carolina - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Total Separations: Total nonfarm in North Carolina - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)', 'Hires: Total nonfarm in North Dakota - Level in Thou

### Addressing Multicollinearity

So, since every column is being highlighted as multicollinear, I have to have different scopes for VIF filtering.

In [19]:
def calculate_vif_for_scope(X):
    X_vif = sm.add_constant(X, has_constant='add')
    
    vif_data = pd.DataFrame()
    vif_data["feature"] = X_vif.columns

    try:
        vif_data["VIF"] = [
            variance_inflation_factor(X_vif.values, i)
            for i in range(X_vif.shape[1])
        ]
        
    except np.linalg.LinAlgError:
        print("\n--- WARNING: Linear Algebra Error (Perfect Multicollinearity persists) ---")
        print("Check if the filtered subset still contains a 'Total' column and all its components.")
        vif_data["VIF"] = "Error"
    
    return vif_data.sort_values(by="VIF", ascending=False)

In [25]:
### National Scope VIF Filtering

national_scope = [
    col for col in jolts_counts.columns
    if "Total nonfarm -" in col and not any(
        s in col for s in ['State and local', 'Federal', 'Private']
    )
]

X_national = jolts_counts[national_scope].copy()

vif_national_df = calculate_vif_for_scope(X_national)

print("="*50)
print("VIF for Scope 1: National Totals")
print(vif_national_df)
print("="*50)

==================================================
VIF for Scope 1: National Totals
                                              feature           VIF
6   Total Separations: Total nonfarm - Level in Th...  9.491818e+06
12  Total Separations: Total nonfarm - Level in Th...  7.872689e+06
3   Layoffs and Discharges: Total nonfarm - Level ...  7.718111e+06
9   Layoffs and Discharges: Total nonfarm - Level ...  6.033967e+06
11  Quits: Total nonfarm - Level in Thousands, Mon...  1.597801e+06
5   Quits: Total nonfarm - Level in Thousands, Mon...  1.469604e+06
10  Other separations: Total nonfarm - Level in Th...  9.411967e+03
4   Other separations: Total nonfarm - Level in Th...  4.055495e+03
0                                               const  2.997347e+02
2   Job Openings: Total nonfarm - Level in Thousan...  1.107250e+02
8   Job Openings: Total nonfarm - Level in Thousan...  1.061695e+02
1   Hires: Total nonfarm - Level in Thousands, Mon...  2.677781e+01
7   Hires: Total nonfarm - Level in Thousands, Mon...  9.293525e+00
==================================================

In [23]:
X_national.head()

,"Hires: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Job Openings: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Layoffs and Discharges: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Other separations: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Quits: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Total Separations: Total nonfarm - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Hires: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Job Openings: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Layoffs and Discharges: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Quits: Total nonfarm in Alabama - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)",...,"Layoffs and Discharges: Total nonfarm in South region - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Other separations: Total nonfarm in South region - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Quits: Total nonfarm in South region - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Total Separations: Total nonfarm in South region - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Hires: Total nonfarm in West region - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Job Openings: Total nonfarm in West region - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Layoffs and Discharges: Total nonfarm in West region - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Other separations: Total nonfarm in West region - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Quits: Total nonfarm in West region - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Total Separations: Total nonfarm in West region - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)"
0,5426.0,5088.0,2018.0,340.0,2882.0,5240.0,78.0,68.0,24.0,38.0,...,653.0,109.0,815.0,1578.0,1114.0,1143.0,579.0,90.0,558.0,1227.0
1,5722.0,5234.0,2220.0,377.0,3245.0,5842.0,81.0,70.0,25.0,45.0,...,930.0,216.0,1275.0,2421.0,1373.0,1391.0,770.0,116.0,799.0,1686.0
2,5303.0,5097.0,1855.0,323.0,3053.0,5231.0,67.0,70.0,28.0,43.0,...,454.0,112.0,968.0,1532.0,1144.0,1140.0,366.0,55.0,510.0,932.0
3,5528.0,4762.0,2133.0,379.0,3054.0,5566.0,86.0,58.0,32.0,42.0,...,488.0,113.0,920.0,1520.0,1194.0,1059.0,417.0,55.0,612.0,1085.0
4,5204.0,4615.0,1883.0,367.0,3163.0,5414.0,86.0,65.0,27.0,48.0,...,606.0,141.0,1224.0,1971.0,1201.0,1163.0,455.0,88.0,779.0,1322.0

In [24]:
granular_columns = [
    col for col in jolts_counts.columns
    if not any(s in col for s in ['Total nonfarm', 'Total Industry', 'All Industry', 'const', 'date']) and
    jolts_counts[col].dtype in ['int64', 'float64']
]

X_granular = jolts_counts[granular_columns].copy()

vif_granular_df = calculate_vif_for_scope(X_granular)

print("="*50)
print("VIF for Scope 3: Granular (State x Industry) Data")
print(vif_granular_df)
print("="*50)

C:\Users\samee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\statsmodels\regression\linear_model.py:1782: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
C:\Users\samee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

==================================================
VIF for Scope 3: Granular (State x Industry) Data
                                               feature  VIF
396  Total Separations: State and local government,...  inf
395  Quits: State and local government, excluding e...  inf
1    Hires: Total private - Level in Thousands, Mon...  inf
2    Job Openings: Total private - Level in Thousan...  inf
3    Layoffs and Discharges: Total private - Level ...  inf
..                                                 ...  ...
15   Layoffs and Discharges: Total private - Level ...  inf
14   Job Openings: Total private - Level in Thousan...  inf
13   Hires: Total private - Level in Thousands, Mon...  inf
12   Total Separations: Total private - Level in Th...  inf
0                                                const  0.0

[397 rows x 2 columns]
==================================================

In [26]:
X_granular.head()

,"Hires: Total private - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Job Openings: Total private - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Layoffs and Discharges: Total private - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Other separations: Total private - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Quits: Total private - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Total Separations: Total private - Level in Thousands, Monthly, Seasonally Adjusted (All size classes)","Hires: Total private - Level in Thousands, Monthly, Seasonally Adjusted (1 to 9 employees)","Job Openings: Total private - Level in Thousands, Monthly, Seasonally Adjusted (1 to 9 employees)","Layoffs and Discharges: Total private - Level in Thousands, Monthly, Seasonally Adjusted (1 to 9 employees)","Other separations: Total private - Level in Thousands, Monthly, Seasonally Adjusted (1 to 9 employees)",...,"Layoffs and Discharges: State and local government education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Other separations: State and local government education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Quits: State and local government education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Total Separations: State and local government education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Hires: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Job Openings: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Layoffs and Discharges: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Other separations: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Quits: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)","Total Separations: State and local government, excluding education - Level in Thousands, Monthly, Not Seasonally Adjusted (All size classes)"
0,5084.0,4541.0,1908.0,296.0,2739.0,4942.0,553.0,567.0,113.0,53.0,...,42.0,11.0,45.0,98.0,105.0,277.0,44.0,19.0,52.0,115.0
1,5385.0,4752.0,2126.0,326.0,3086.0,5538.0,605.0,752.0,194.0,81.0,...,22.0,16.0,58.0,96.0,127.0,255.0,33.0,23.0,56.0,112.0
2,4938.0,4619.0,1756.0,275.0,2885.0,4917.0,652.0,635.0,64.0,55.0,...,19.0,11.0,40.0,70.0,124.0,242.0,27.0,16.0,72.0,115.0
3,5182.0,4316.0,2033.0,336.0,2889.0,5259.0,582.0,602.0,196.0,38.0,...,13.0,11.0,45.0,69.0,128.0,243.0,26.0,17.0,68.0,111.0
4,4871.0,4125.0,1791.0,315.0,3032.0,5139.0,572.0,436.0,267.0,33.0,...,12.0,12.0,34.0,59.0,143.0,288.0,48.0,22.0,57.0,127.0